matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "6"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint && cd ..
    - stage: "Build and Test"
      env:
        - BuildAndroid="25"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build android && cd ..
    - os: osx
      env:
        - BuildiOS="10.3"
        - Xcode="8.3"
      osx_image: xcode8.3
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build ios && cd ..

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable